title:            Blossom
description:      A jekyll theme. Because I scribble.
url:              # Site url.
signoff:          # Your name.
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         Brief
    url:          /about
  - name:         Blog
    url:          /
  - name:         Aperture
    url:          mailto:hello@muan.co
    external:     true
  - name:         Note
    url:          /note
pygments:         true
permalink:        pretty
markdown:         rdiscount
rdiscount:
  extensions:     [smart]